---
title: "Project Proposal"
author: "Rated R - Carlie Scheer, Christina Lee, Jerry Lin, Samir Travers"
format: pdf
execute: 
  warning: false
  message: false
editor: visual
---

```{r}
#| label: load-pkg-data
library(tidyverse)
library(tidymodels)
library(knitr)

library(readr)
final_movie_data <- read_csv("data/final_movie_data.csv")
```

## Introduction

Movies have been at the heart of pop culture for nearly a century. And while movies have changed a lot over the years, varying in length, theme, due to technological advances, and more, one thing has never changed–movies have remained as a dominant part of the entertainment industry. Yet, ever since the COVID-19 pandemic, the North American box office for movies has not recovered–it seems that people just aren’t going to movies as much as they used to. Domestic box office gross revenue in 2019 reached nearly \$11.4 billion, while the yearly total from 2023 topped off at \$8.9 billion after a very slow two years in 2020 and 2021 (Box Office Mojo). With moviegoers back on the rise, the film industry and box offices are hopeful to end the decade on a high note and return back to their original state. As such, we are interested in investigating the trends in gross revenue for top movies and how various elements impact the amount of money that a movie makes.

“Domestic Yearly Box Office.” Box Office Mojo, 2 Oct. 2024, www.boxofficemojo.com/year/. Accessed 2 Oct. 2024.

Research Question: What are the key factors and metrics that most significantly influence a movie's gross revenue?

Motivation: As a group of movie enthusiasts, movie popularity has always been a large source of curiosity. We’ve seen terrible movies whose popularity we find puzzling, and unknown masterpieces that do not get the attention they deserve. What is it that separates the two? Is it primarily the “goodness” of the movie that determines the money it brings in, or are there other factors that are equally influential? Is the 1.4 billion dollar success of Alvin and the Chipmunks (an objectively pretty bad movie) just an outlier, or reflective of a deep and complex relationship between a movie’s characteristics and its gross profit? Through our analysis, we hope to get to the bottom of these questions, and gain a deeper understanding of what truly drives a movie's success or failure in the box office.

Hypotheses: We hypothesize movies that have high popularity scores and ratings, substantial budgets, and broad audience appeal will be more likely to generate higher gross revenue. We also hypothesize movies with more than one genre will be more likely to generate higher gross revenue. Movies with a runtime between 1.5-2 hours will be more likely to generate higher gross revenue.

## Data description

The source of the dataset is taken from TMDb (The Movie Database), which is an online, public database for movies that contains information such as ratings, runtime, cast, director, and box office performance.

We discovered this dataset at this link on Kaggle: <https://www.kaggle.com/datasets/asaniczka/tmdb-movies-dataset-2023-930k-movies> and it is updated daily by user asaniczka, who takes the data from TMDb. 

There are 953629 observations in this dataset, each representing a single film. There are 24 columns in this dataset, with some of the most important being the name (an identifier), release year, runtime, genres, rating, votes, and revenue.

## Exploratory data analysis

We filtered the dataset because the original dataset was far too large to be able to run efficiently in RStudio: Firstly, we filtered to only include recent movies, from 2019 to 2025. Then, we filtered for movies where the original language is english. Lastly, we filtered for where the movies had more than 100 votes. (EDIT THIS, THIS IS PART OF EDA, AND ADD ON THAT WE WILL FILTER FURTHER BY THINGS SUCH AS RELEASE STATUS)

## Analysis approach

...

## Data dictionary

The data dictionary can be found <https://labs-az-08.oit.duke.edu:30174/files/project-Rated-R/data/README.html>
